


const english ={
    loading: "loading...",
    agree: "Agree",
    he_is_a: "He is a",
    alive: "alive",
    dead: "dead",
    vote: "Vote",
    click_see_testament: "Click here to see the testament",
    type_testament: "Type of Testament",
    Details_Vote: "Vote Details",
    user_interaction: "Interacting Users",
    warning_vote: "If you are not sure about the death of this person, please refrain from voting and violating the site's terms and conditions, as it may result in a permanent ban on your account",
    notice: "Notice",
    note_1: "1- Please read how to use this website before voting to comply with the site's terms and conditions.",
    note_2: "2- Make sure you know about the death of this person",
    note_3: "3- If you are already sure about their death, please vote.",
    note_4: "4- Be honest when voting and don't let greed push you to vote if this person is still alive.",
    name: "Name",
    email: "Email",
    password: "Password",
    submit: "Submit",
    cancel: "Cancel",
    Receive: "Receive",
    complete: "Voting Completed",
    isPublic: "No Details",
    isInteraction: "No User Interaction",
    number_of_voting: "Number of Voters",
    total_number_of_voting: "Total Number of Votes",
    remain_votes: "Remaining Votes",
    testament: "Testament",
    receive_special_friend: "Receiving Special Friends",
    voting_special_friends: "Voting Special Friends",
    title_voting_users: "Users Voting",
    description_voting_users: "Are you sure you want to vote?",
    error_user_cannot_like: "You cannot vote, please login",
    error_check_data_specialFriend: "Please check again. The information you provided is not accurate.",
    error_check_data_receiveFriend: "You are not authorized to view the testament",
    error_already_vote: "You have already voted",
    title_voting: "Vote for your deceased friends",
    description_meta_voting: "Vote for your deceased friends, Vote, Like to see your deceased friend's testament, Death, Deceased, Azrael, My friend's testament, View the testament, How to write a testament, Create a testament, Get a testament"
}
const arabic={
    loading: "جاري التحميل...",
    agree: "موافق",
    he_is_a: "انه ",
    alive: "على قيد الحياة",
    dead: "متوفي",
    vote: "صوت",
    click_see_testament: "انقر هنا لرؤية الوصية",
    type_testament: "نوع الوصية",
    Details_Vote: "تفاصيل التصويت",
    user_interaction: "المستخدمين المتفاعلين",
    warning_vote: "إذا لم تكن متأكدًا من وفاة هذا الشخص، يرجى عدم التصويت وعدم انتهاك شروط الموقع، حيث يمكن أن يؤدي ذلك إلى حظر دائم على حسابك",
    notice: "ملاحظة",
    note_1: "1- يرجى قراءة كيفية استخدام هذا الموقع قبل التصويت للامتثال لشروط وأحكام الموقع.",
    note_2: "2- تأكد من معرفتك بوفاة هذا الشخص",
    note_3: "3- إذا كنت بالفعل متأكدًا من وفاتهم، يرجى التصويت.",
    note_4: "4- كن صادقًا عند التصويت ولا تدع الطمع يدفعك للتصويت إذا كان هذا الشخص لا يزال على قيد الحياة.",
    name: "الاسم",
    email: "الايميل",
    password: "كلمة السر",

    submit: "ارسال",
    cancel: "الغاء",
    Receive: "استلام",
    complete: "انتهى التصويت",
    isPublic: "لايوجد تفاصيل",

    isInteraction: "لايوجد تفاعل للمستخدمين",
    number_of_the_voting: "عدد المصوتين",
    total_number_of_the_voting: "المجموع الكلي للاصوات",
    remain_votes: "الاصوات المتبقية",
    testament: "الوصية",
    receive_special_friend: "الاصدقاء الخاصيين المستلمين",
    voting_special_friends: "تصويت الاصدقاء الخاصيين",
    title_voting_users: "تصويت المستخدمين",
    description_voting_users: "هل انت متاكد من التصويت؟",
    error_user_cannot_like: "انت لاتستيطع التصويت يرجى تسجيل الدخول",
    error_check_data_specialFriend: "من فضلك قم بالتحقق مرة أخرى. المعلومات التي قمت بإدخالها غير دقيقة",
    error_check_data_receiveFriend: "انت غير مصرح لك بمشاهدة الوصية",

    error_already_vote: "أنت بالفعل قمت بالتصويت",


    title_voting: "صوت لاصدقائك الاموات",
    description_meta_voting: "صوت لاصدقائك الاموات,صوت,ضع لايك لتشاهد وصية صديقك المتوفي,الموت,الوفاة,عزرائيل,وصية صديقي,مشاهدة الوصية,كيف اكتب وصية,انشاء وصية,الحصول على وصية,"
}

export {english,arabic}